### PR TITLE
Focus to output panel after test

### PR DESCRIPTION
**Pull request by Xiaohong-Deng**
In RSpec test, often the feedback is more than one screen can fit even if the output panel is maximized. We need to scroll up and down to read the information. In order not to move our hands away from keyboard, it's nice to have the output panel focused after the test is run such that we can scroll up and down right away using keyboard.

This change will affect **Test Current Line** and **Test Current File**.

Another related useful feature is reopen the output panel and focus on it. We need to maximize the panel to read the test feedback. After that in order to code, we have to close it. Often we need to recheck what the error message is which makes this feature useful. This is a small but yet independent feature. This feature could be useful to other needs with other plugins. Might as well leave it as a separate plugin instead of merging it to yours. What you think?

### CODE REVIEW

**Comment by astrauka** [comment]
@Xiaohong-Deng I believe this is a nice feature.
There are two cases:

* output fits into the screen and I can read the output without losing focus from the code that I am writing - especially when the spec is green
* output does not fit the screen and I need to scroll the spec output

Could we make the functionality configurable?

* extract [focusing](https://github.com/astrauka/TestRSpec/pull/23/files#diff-a618f6be30c9dfd74b38709811a814a7R15) to a separate method `_focus_test_panel`
* create settings configuration variable `focus_test_panel`
* in the extracted method check if the configuration is set to `true` and focus if that's the case

What do you think about it?

**Comment by Xiaohong-Deng** [comment]
Yes. That'll be nice. I'll get back to you when I figure out how to make that happen.

How do I reuse this PR in order to keep this thread while using a new commit to do the merge?

**Comment by astrauka** [comment]
This can be achieved by ammending the changes with `git commit --ammend`.
Or you can create a new branch `git checkout -b feature/focus_test_panel`, cherry pick the commit `git cherry-pick 23bdef2`, then make more commits and finally create a new PR in which you just paste the link to this PR. Then we could close this one and continue working on the new one.
Good post on how to write Sublime plugin - http://engineering.vinted.com/2016/06/27/how-to-write-sublime-plugin/

**Comment by OlegSmelov** [comment]
Closing because of inactivity. Feel free to update the code and reopen this pull request.

**Pull request closed without merging**
