### PR TITLE
Add setting to ignore nested classes

### PR DESCRIPTION
**Pull request by badBlackShark**
Hi :)

First of all, I barely know any Python and only edited this using the GitHub UI. I love this package, but I personally need spec files for a lot of nested classes. The needed folder structure is supported, but when creating the spec the template class name breaks too early for me. To not change existing behavior I added a setting that determines whether the current behavior should stay (default), or whether nested classes should be counted for the class name.

This would be an amazing edition for me!

Thank you!

### CODE REVIEW

**Comment by OlegSmelov** [comment]
Hi! I'm trying to understand the use case for this. Can you please provide some code samples? What I'm trying to understand is that why nested classes are necessary, or in other words: 1. why isn't the parent class a module, or 2. why isn't the child class in a separate file. 🤔

**Comment by badBlackShark** [comment]
Hi! So we use the gem [Remap](https://github.com/oleander/remap) a lot at work, which is where I primarily use this plugin. As such, you can have something like
```rb
module Project
  class Mapper < Remap::Base
    define do
      embed ChildMapper
    end
  end
end
```
and then the aforementioned `ChildMapper`:
```rb
module Project
  class Mapper
    class ChildMapper < Remap::Base
      define do
        map(:name, to: :first_name)
        # ...
      end
    end
  end
end
```

Now when I go to create a spec file for the `ChildMapper`, it extracts only `Project::Mapper`. I however need `Project::Mapper::ChildMapper`. I need this to be subclassed, too, since there's different mappers that have the same name (e.g. there's many places where we map children, but the exact data and target structure is different, so they need to live in different namespaces). The parent can't be modules, because they're also mappers. The child *is* in a different file 😄

**Comment by OlegSmelov** [comment]
Makes more sense now. 👍 I'll give this some testing then to make sure the change works.

However, keep in mind that the code is not very smart and doesn't take nesting into account, so something like

```ruby
module A
  class B
    class C; end
  end
end

class D; end
```

will create a spec for `A::B::C::D` with `ignore_nested_classes` disabled. Previously it would create a spec for `A::B`.

**Comment by badBlackShark** [comment]
That's a fair point for sure. An argument could be made that that kind of nesting might not be a desirable pattern anyway, I guess? But either way, by making this an option at the very least we're not losing the previous behavior. If it comes down to it someone can always improve the algorithm in the future.

**Comment by OlegSmelov** [comment]
Thank you for your contribution!

Released as v2.2.0. It should appear soon enough [on Package Control](https://packagecontrol.io/packages/TestRSpec). 😄

**Pull request merged**
